### ISSUE TITLE
confusion in the computation of e_k

### ISSUE THREAD

**Issue by yu-jiang** [rawify/Stewart.js#1]
Hi

The code is very nicely written. I can follow the logic easily. However, I am having a confusion regarding the computation of e_k

https://github.com/infusion/Stewart/blob/def4b9117bd66f1299c3c641278d27717fd27daa/stewart.js#L1198

Should `l[2][2]`be `li[2]` or `l[i][2]`? According to the webpage

 https://www.xarg.org/paper/inverse-kinematics-of-a-stewart-platform/

It should be 

![image](https://user-images.githubusercontent.com/10866615/91877679-51119d80-ec4c-11ea-8cd4-a744a9a41b57.png)

I guess the first index [2] is a typo. Is that right?

**Comment by infusion** [comment]
Thanks a lot! This is a pretty good finding and yes it is a typo! I fixed and published a new version! May I ask what you're building with it? :)

**Comment by yu-jiang** [comment]
Thanks for the quick update and glad to know my comment was helpful. This project is well written and I think it is the best tutorial for me to start learning the basics of Stewart platform. I am trying to study vehicle dynamics with it.
